---
title: "Dogs' Metagenomes Figure2"
author: "Xiaoyang Wang"
date: "11/28/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Figure 2A
```{r Function }
library(tidyverse)
library(forcats)
library(openxlsx)
library(ggnewscale)

df <- read.table('../data/all_kegg_enrich0830.txt', sep = "\t", header = TRUE)
df$generatio <- df$Group1_genes/as.numeric(df$Group1_total)
unique(df$Level1)

df <-  df %>% filter(Level1=='Metabolism') %>% 
  filter(fdr<=0.05) %>% 
  filter(generatio>=0.005)

df$fdr <- ifelse(df$fdr == 0, 1.000000e-299, df$fdr)

df$class <- paste(df$Group1,df$Group2,sep = '_')
#write.table(df,'all_KEGG_enrich.txt',col.names = NA,quote = F,sep = '\t')

df$Pathway_Info <- as.factor(df$Pathway_Info)
df$Pathway_Info <- fct_inorder(df$Pathway_Info)

df$ratio1 <- as.numeric(df$Group1_genes)/as.numeric(df$Group1_total)
df$ratio2 <- as.numeric(df$Group2_genes)/as.numeric(df$Group2_total)

df1<- df %>% filter(ratio1>ratio2) 
df1$class <- paste(df1$Group1,df1$Group2,sep = '_')
df1$fdr <- as.numeric(df1$fdr)

df2 <- df %>% filter(ratio1<ratio2)
df2$class <- paste(df2$Group1,df2$Group2,sep = '_')

# data$Level2 <- as.factor(data$Level2)
df2$fdr <- as.numeric(df2$fdr)


data <- rbind(df1,df2)
data$fdr <- as.numeric(data$fdr)
data$Pathway_Info<- as.factor(data$Pathway_Info)
data <- data[order(data$Level2),] 

unique(data$class)
p1 <- ggplot(data, aes(class, Pathway_Info)) +
  geom_point(data=df1,aes(color=-log(fdr),size=generatio),
             shape=19,position = position_nudge(x = -0.15))+
  geom_point(data=df2,aes(color=-log(fdr),size=generatio),
             shape=21,position = position_nudge(x = -0.15))+
  scale_colour_gradient2(mid='#FFA07A', high="#ee4000",midpoint = 2)+
  # scale_colour_gradient2(low='#FFA07A', mid='#ff7759',high="#ee2f48",midpoint = 2)+
  scale_color_distiller(palette = "Reds", direction = 1)+
  new_scale_color()+
  geom_point(data=df2,aes(color=-log(fdr),size=generatio),
             shape=19,position = position_nudge(x = 0.15))+
  geom_point(data=df1,aes(color=-log(fdr), size=generatio),
             shape=21,position = position_nudge(x = 0.15))+
  scale_colour_gradient2(mid ='#c3e6ce',high="#006400",midpoint = 2)+
  theme(axis.text.x=element_text(angle=90,hjust = 1,vjust=0.5))+
  labs(x=NULL,y=NULL)+guides(size=guide_legend(order=1))+
  guides(color = guide_colorbar(ticks = TRUE, barheight = 6,frame.colour = "black"))+
  theme_classic()+
  scale_size(range = c(0.5,4.5))+
  labs(x = "", y = "", 
       fill = "-log(FDR)", 
       size = "Gene_Ratio",title = 'KEGG Function of Metabolism')+
  theme(axis.text = element_text(size = 10,face = 'bold'),axis.line = element_line(size = 1),
        #axis.text.x  = element_text(angle = 90),
        axis.ticks = element_blank(),plot.title = element_text(size = 15,face = 'bold'))

p1+facet_grid(Level2~.,space="free",scales = "free",switch = "y")+
  theme(strip.text = element_text(size = 10,colour = "black"),
        strip.placement = "outside")

```

# Figure 2B
```{r ReporterScore, for shared SGBs}
# install.packages("ggstatsplot")
# install.packages("devtools")
# devtools::install_github('Asa12138/ReporterScore',dependencies=T)
library(ReporterScore)
library(dplyr)
library(ggplot2)
library(ggnewscale)
library(reshape2)
library(ggraph)

library(readr)
#KEGG pathway-KO and module-KO databases
load_KOlist()
# head(KOlist$pathway)
# KEGG pathway-compound and module-compound databases
load_CPDlist()
load_GOlist()

# KO data and metadata
KO_abundance <- read.table("../data/dog_PW_KO.txt", header = T)

row.names(KO_abundance) <- KO_abundance$KEGG_ko
KO_abundance <- KO_abundance[, -1]
metadata <- read.table("../data/group_data_Dpw.txt", header = T)

row.names(metadata) <- metadata$Sample
metadata <- metadata[, -1]

cat("Comparison: ",levels(factor(metadata$Group1)))

reporter_score_res=reporter_score(KO_abundance,"Group1",metadata,mode="directed",method = "wilcox.test")

# Plot the most significantly enriched pathways
plot_report(reporter_score_res,rs_threshold = c(-2.5,2.5), facet_anno = TRUE)
# plot_report(reporter_score_res,rs_threshold = c(-4.5,4.5))

# Plot the most significantly enriched pathways (circle packing)
plot_report_circle_packing(reporter_score_res,rs_threshold = c(-2.5,2.5)) 

```


